export const POST_ADDPRODUCTS_REQUEST = 'POST_ADDPRODUCTS_REQUEST';
export const POST_ADDPRODUCTS_SUCCESS = 'POST_ADDPRODUCTS_SUCCESS';
export const POST_ADDPRODUCTS_FAILURE = 'POST_ADDPRODUCTS_FAILURE';