export const POST_ADDPRODUCTS_REQUEST = 'POST_ADDPRODUCTS_REQUEST';
export const POST_ADDPRODUCTS_SUCCESS = 'POST_ADDPRODUCTS_SUCCESS';
export const POST_ADDPRODUCTS_FAILURE = 'POST_ADDPRODUCTS_FAILURE';

export const GET_ADDPRODUCTS_REQUEST = 'GET_ADDPRODUCTS_REQUEST';
export const GET_ADDPRODUCTS_SUCCESS = 'GET_ADDPRODUCTS_SUCCESS';
export const GET_ADDPRODUCTS_FAILURE = 'GET_ADDPRODUCTS_FAILURE';